name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build with Buildozer
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clone repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 🛠️ Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-11-jdk \
            python3-pip python3-setuptools \
            python3-dev build-essential \
            libncurses5 libstdc++6 libffi-dev \
            libssl-dev libsqlite3-dev zlib1g-dev \
            libncursesw5-dev libreadline6-dev \
            libgdbm-dev libbz2-dev liblzma-dev \
            libxml2-dev libxslt1-dev libjpeg-dev

          pip install --upgrade pip Cython virtualenv
          pip install buildozer

      - name: 📦 Build APK
        run: |
          buildozer android debug

      - name: 📤 Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: 7alpha-app-apk
          path: bin/*.apk